/**
 * Historical culture profiles for on-the-fly tribe creation.
 * Each profile supplies Travian-style 11-slot rosters + hero, flavored by era/region.
 *
 * Balance targets stay within existing Tevel / Travian Legends ranges so new tribes
 * compare fairly in table, graphics, charts, and normalized stat views.
 */

/** @typedef {{ attack: number, defenseInfantry: number, defenseCavalry: number, speed: number, carry: number }} Stats */
/** @typedef {{ wood: number, clay: number, iron: number, crop: number }} Cost */
/** @typedef {{ name: string, stats: Stats, cost: Cost, cropUpkeep: number, description?: string }} TroopDef */

/**
 * @typedef {object} CultureProfile
 * @property {string} id
 * @property {string} name
 * @property {string} era
 * @property {string} region
 * @property {string} theme
 * @property {string} historicalContext
 * @property {string[]} keywords
 * @property {{ primary: string, secondary: string, notes: string }} palette
 * @property {'infantry'|'cavalry'|'balanced'|'raider'} archetype
 * @property {number} fightingStrengthPerPoint
 * @property {number} [resourceProductionBonusPercent]
 * @property {Record<string, string>} logos
 * @property {Record<string, { building: string, timeSeconds: number }>} training
 * @property {Record<string, TroopDef>} troops
 * @property {{ name: string, description: string, stats: Stats, cropUpkeep: number }} hero
 */

/** @type {CultureProfile[]} */
export const CULTURE_PROFILES = [
  {
    id: "carthaginian",
    name: "Carthaginians",
    era: "Punic Wars (3rd–2nd c. BCE)",
    region: "North Africa / western Mediterranean",
    theme: "Mercenary armies, elephants, and naval wealth — soft core infantry, elite mounted punch",
    historicalContext:
      "Carthage fielded mixed mercenary hosts: Libyan spearmen, Balearic slingers, Numidian light horse, and war elephants, financed by Mediterranean trade.",
    keywords: ["carthage", "carthaginian", "punic", "hannibal", "phoenician", "numidian", "elephant"],
    palette: { primary: "#1B4F72", secondary: "#C9A227", notes: "Tyrian sea-blue + trade gold" },
    archetype: "balanced",
    fightingStrengthPerPoint: 90,
    resourceProductionBonusPercent: 10,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/boomerang.svg",
      inf_t3: "infantry/battle-axe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "cavalry/elephant.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/orb-wand.svg",
      settler: "resources/cash-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1200 },
      inf_t2: { building: "barracks", timeSeconds: 1440 },
      inf_t3: { building: "barracks", timeSeconds: 1680 },
      scout: { building: "barracks", timeSeconds: 1280 },
      cav_t1: { building: "stable", timeSeconds: 1600 },
      cav_t2: { building: "stable", timeSeconds: 2200 },
      cav_t3: { building: "stable", timeSeconds: 2800 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Libyan Spearman",
        description: "Levy spearmen from Libyan subject cities — solid line infantry.",
        stats: { attack: 35, defenseInfantry: 40, defenseCavalry: 45, speed: 6, carry: 45 },
        cost: { wood: 110, clay: 95, iron: 120, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Balearic Slinger",
        description: "Famous island skirmishers — weak in melee, strong vs unarmored hosts.",
        stats: { attack: 45, defenseInfantry: 25, defenseCavalry: 20, speed: 8, carry: 30 },
        cost: { wood: 130, clay: 80, iron: 55, crop: 45 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Sacred Band",
        description: "Citizen elite of Carthage — costly, disciplined heavy infantry.",
        stats: { attack: 65, defenseInfantry: 55, defenseCavalry: 40, speed: 6, carry: 50 },
        cost: { wood: 160, clay: 150, iron: 200, crop: 90 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Numidian Scout",
        description: "Light riders used for reconnaissance across Maghreb plains.",
        stats: { attack: 0, defenseInfantry: 18, defenseCavalry: 12, speed: 17, carry: 0 },
        cost: { wood: 130, clay: 140, iron: 25, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Numidian Cavalry",
        description: "Swift javelin horsemen — Hannibal’s screening and pursuit arm.",
        stats: { attack: 110, defenseInfantry: 50, defenseCavalry: 45, speed: 16, carry: 90 },
        cost: { wood: 480, clay: 380, iron: 280, crop: 95 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Punic Noble Horse",
        description: "Armored citizen cavalry for decisive charges.",
        stats: { attack: 165, defenseInfantry: 70, defenseCavalry: 95, speed: 11, carry: 70 },
        cost: { wood: 540, clay: 600, iron: 720, crop: 170 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "War Elephant",
        description: "North African elephants — shock vs infantry, slow and costly.",
        stats: { attack: 175, defenseInfantry: 85, defenseCavalry: 55, speed: 8, carry: 40 },
        cost: { wood: 600, clay: 520, iron: 650, crop: 220 },
        cropUpkeep: 5,
      },
      ram: {
        name: "Siege Ram",
        stats: { attack: 55, defenseInfantry: 30, defenseCavalry: 70, speed: 4, carry: 0 },
        cost: { wood: 880, clay: 350, iron: 480, crop: 70 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Stone Thrower",
        stats: { attack: 70, defenseInfantry: 55, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 920, clay: 1300, iron: 580, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Suffete",
        description: "Elected magistrate-general empowered to receive cities.",
        stats: { attack: 45, defenseInfantry: 40, defenseCavalry: 30, speed: 4, carry: 0 },
        cost: { wood: 30000, clay: 27000, iron: 44000, crop: 36000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Colonist",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5600, clay: 5200, iron: 7000, crop: 5400 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Punic Hero",
      description: "Carthaginian commander in the mold of Barcid generals — cavalry and elephant coordination.",
      stats: { attack: 105, defenseInfantry: 110, defenseCavalry: 105, speed: 9, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "persian",
    name: "Persians",
    era: "Achaemenid Empire (6th–4th c. BCE)",
    region: "Iranian plateau / Near East",
    theme: "Vast levy infantry, Immortals, and horse archers of the Great King",
    historicalContext:
      "Achaemenid armies combined subject levies with elite Immortals and Median/Persian cavalry; logistics and numbers mattered as much as shock.",
    keywords: ["persian", "persia", "achaemenid", "immortal", "darius", "xerxes", "median", "iran"],
    palette: { primary: "#6B2D5C", secondary: "#E8C547", notes: "Royal purple + sun gold" },
    archetype: "balanced",
    fightingStrengthPerPoint: 85,
    resourceProductionBonusPercent: 15,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/heavy-arrow.svg",
      inf_t3: "infantry/flanged-mace.svg",
      scout: "infantry/arrowhead.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "cavalry/camel-head.svg",
      ram: "infantry/war-pick.svg",
      catapult: "powder.svg",
      chief: "infantry/crescent-staff.svg",
      settler: "resources/grain.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 900 },
      inf_t2: { building: "barracks", timeSeconds: 1200 },
      inf_t3: { building: "barracks", timeSeconds: 1600 },
      scout: { building: "barracks", timeSeconds: 1120 },
      cav_t1: { building: "stable", timeSeconds: 1680 },
      cav_t2: { building: "stable", timeSeconds: 2100 },
      cav_t3: { building: "stable", timeSeconds: 2300 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Sparabara",
        description: "Shield-bearer levy with spear and large pavise.",
        stats: { attack: 30, defenseInfantry: 45, defenseCavalry: 35, speed: 6, carry: 40 },
        cost: { wood: 100, clay: 90, iron: 80, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Takabara Archer",
        description: "Shielded bowmen supporting the battle line.",
        stats: { attack: 50, defenseInfantry: 30, defenseCavalry: 25, speed: 7, carry: 35 },
        cost: { wood: 140, clay: 90, iron: 60, crop: 50 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Immortal",
        description: "10,000 household infantry — elite of the Great King.",
        stats: { attack: 75, defenseInfantry: 50, defenseCavalry: 35, speed: 7, carry: 50 },
        cost: { wood: 170, clay: 160, iron: 220, crop: 95 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Mounted Scout",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 10, speed: 16, carry: 0 },
        cost: { wood: 135, clay: 150, iron: 20, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Median Horseman",
        stats: { attack: 115, defenseInfantry: 55, defenseCavalry: 50, speed: 15, carry: 95 },
        cost: { wood: 500, clay: 400, iron: 300, crop: 100 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Persian Cataphract",
        description: "Early heavy horse with scale and kontos.",
        stats: { attack: 170, defenseInfantry: 85, defenseCavalry: 100, speed: 10, carry: 65 },
        cost: { wood: 560, clay: 620, iron: 780, crop: 180 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Camel Corps",
        description: "Desert camelry — unsettling to untrained horses.",
        stats: { attack: 140, defenseInfantry: 60, defenseCavalry: 70, speed: 12, carry: 110 },
        cost: { wood: 480, clay: 450, iron: 420, crop: 150 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Siege Ram",
        stats: { attack: 60, defenseInfantry: 30, defenseCavalry: 75, speed: 4, carry: 0 },
        cost: { wood: 900, clay: 360, iron: 500, crop: 70 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Siege Engine",
        stats: { attack: 75, defenseInfantry: 60, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 950, clay: 1350, iron: 600, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Satrap",
        stats: { attack: 50, defenseInfantry: 40, defenseCavalry: 30, speed: 4, carry: 0 },
        cost: { wood: 31000, clay: 27500, iron: 45000, crop: 37000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5800, clay: 5300, iron: 7200, crop: 5500 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Persian Hero",
      description: "Achaemenid royal companion — levy coordination and cavalry screens.",
      stats: { attack: 95, defenseInfantry: 115, defenseCavalry: 100, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "viking",
    name: "Vikings",
    era: "Viking Age (8th–11th c. CE)",
    region: "Scandinavia / North Sea",
    theme: "Raid-focused infantry, cheap aggression, limited heavy cavalry",
    historicalContext:
      "Norse warbands excelled at coastal raids and shield-wall fighting; horses were secondary to ships and axes.",
    keywords: ["viking", "norse", "scandinavia", "danish", "norwegian", "swedish", "varangian", "berserker"],
    palette: { primary: "#1A3A5C", secondary: "#A8B4C0", notes: "Fjord blue + iron silver" },
    archetype: "raider",
    fightingStrengthPerPoint: 85,
    logos: {
      inf_t1: "infantry/wood-club.svg",
      inf_t2: "infantry/battle-axe.svg",
      inf_t3: "infantry/war-axe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/donkey.svg",
      cav_t2: "cavalry/horse-head.svg",
      cav_t3: "cavalry/chess-knight.svg",
      ram: "infantry/battered-axe.svg",
      catapult: "powder.svg",
      chief: "infantry/thor-hammer.svg",
      settler: "resources/wood-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 720 },
      inf_t2: { building: "barracks", timeSeconds: 1040 },
      inf_t3: { building: "barracks", timeSeconds: 1280 },
      scout: { building: "barracks", timeSeconds: 1120 },
      cav_t1: { building: "stable", timeSeconds: 1500 },
      cav_t2: { building: "stable", timeSeconds: 2000 },
      cav_t3: { building: "stable", timeSeconds: 2200 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 30000 },
    },
    troops: {
      inf_t1: {
        name: "Bondi",
        description: "Free farmer-warrior with spear and shield.",
        stats: { attack: 40, defenseInfantry: 30, defenseCavalry: 20, speed: 7, carry: 50 },
        cost: { wood: 85, clay: 70, iron: 55, crop: 30 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Hirdman",
        description: "Retinue axe-and-shield infantry.",
        stats: { attack: 55, defenseInfantry: 45, defenseCavalry: 25, speed: 6, carry: 40 },
        cost: { wood: 110, clay: 100, iron: 140, crop: 55 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Berserker",
        description: "Shock infantry — high attack, brittle defense.",
        stats: { attack: 85, defenseInfantry: 30, defenseCavalry: 20, speed: 8, carry: 45 },
        cost: { wood: 145, clay: 120, iron: 190, crop: 70 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Scout",
        stats: { attack: 0, defenseInfantry: 15, defenseCavalry: 10, speed: 15, carry: 0 },
        cost: { wood: 120, clay: 130, iron: 20, crop: 35 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Raider Horse",
        stats: { attack: 100, defenseInfantry: 45, defenseCavalry: 40, speed: 15, carry: 110 },
        cost: { wood: 420, clay: 350, iron: 260, crop: 85 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Huscarl Rider",
        stats: { attack: 145, defenseInfantry: 65, defenseCavalry: 80, speed: 11, carry: 75 },
        cost: { wood: 500, clay: 520, iron: 650, crop: 150 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Jarl’s Guard",
        stats: { attack: 155, defenseInfantry: 70, defenseCavalry: 85, speed: 12, carry: 80 },
        cost: { wood: 520, clay: 540, iron: 680, crop: 160 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Ram",
        stats: { attack: 65, defenseInfantry: 25, defenseCavalry: 70, speed: 4, carry: 0 },
        cost: { wood: 850, clay: 340, iron: 480, crop: 65 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Catapult",
        stats: { attack: 70, defenseInfantry: 50, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 900, clay: 1250, iron: 560, crop: 85 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Jarl",
        stats: { attack: 55, defenseInfantry: 35, defenseCavalry: 25, speed: 5, carry: 0 },
        cost: { wood: 28000, clay: 25000, iron: 40000, crop: 34000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5500, clay: 5000, iron: 6800, crop: 5200 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Norse Hero",
      description: "Sea-king war-leader — raid tempo and infantry shock.",
      stats: { attack: 120, defenseInfantry: 95, defenseCavalry: 85, speed: 9, carry: 120 },
      cropUpkeep: 6,
    },
  },
  {
    id: "byzantine",
    name: "Byzantines",
    era: "Eastern Roman Empire (6th–11th c. CE)",
    region: "Anatolia / Balkans / eastern Mediterranean",
    theme: "Cataphracts, disciplined themes, and combined-arms doctrine",
    historicalContext:
      "Byzantine armies emphasized professional cavalry (cataphracts), thematic infantry, and engineered siegecraft inherited from Rome.",
    keywords: ["byzantine", "byzantium", "eastern roman", "cataphract", "constantinople", "theme", "greek fire"],
    palette: { primary: "#2C3E6B", secondary: "#D4AF37", notes: "Imperial blue + mosaic gold" },
    archetype: "cavalry",
    fightingStrengthPerPoint: 95,
    logos: {
      inf_t1: "infantry/gladius.svg",
      inf_t2: "infantry/stone-spear.svg",
      inf_t3: "infantry/crossbow.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "cavalry/elephant.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/baton.svg",
      settler: "resources/brick-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1400 },
      inf_t2: { building: "barracks", timeSeconds: 1600 },
      inf_t3: { building: "barracks", timeSeconds: 1800 },
      scout: { building: "stable", timeSeconds: 1360 },
      cav_t1: { building: "stable", timeSeconds: 2200 },
      cav_t2: { building: "stable", timeSeconds: 2800 },
      cav_t3: { building: "stable", timeSeconds: 3000 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Skutatos",
        description: "Thematic heavy infantry with spear and large shield.",
        stats: { attack: 38, defenseInfantry: 50, defenseCavalry: 55, speed: 5, carry: 45 },
        cost: { wood: 125, clay: 110, iron: 155, crop: 40 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Akontistes",
        description: "Javelin light infantry screening the line.",
        stats: { attack: 40, defenseInfantry: 35, defenseCavalry: 30, speed: 8, carry: 35 },
        cost: { wood: 115, clay: 95, iron: 90, crop: 45 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Toxotes",
        description: "Professional archers of the tagmata / themes.",
        stats: { attack: 60, defenseInfantry: 35, defenseCavalry: 25, speed: 7, carry: 40 },
        cost: { wood: 155, clay: 140, iron: 120, crop: 70 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Prokoursator",
        stats: { attack: 0, defenseInfantry: 22, defenseCavalry: 12, speed: 16, carry: 0 },
        cost: { wood: 145, clay: 160, iron: 25, crop: 45 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Trapezites",
        description: "Light cavalry for pursuit and screening.",
        stats: { attack: 125, defenseInfantry: 60, defenseCavalry: 55, speed: 15, carry: 95 },
        cost: { wood: 540, clay: 430, iron: 330, crop: 105 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Cataphract",
        description: "Fully armored shock cavalry — Byzantine signature.",
        stats: { attack: 190, defenseInfantry: 90, defenseCavalry: 110, speed: 9, carry: 60 },
        cost: { wood: 580, clay: 680, iron: 850, crop: 200 },
        cropUpkeep: 5,
      },
      cav_t3: {
        name: "Klibanophoros",
        description: "Super-heavy household cavalry.",
        stats: { attack: 175, defenseInfantry: 95, defenseCavalry: 115, speed: 8, carry: 55 },
        cost: { wood: 600, clay: 700, iron: 900, crop: 210 },
        cropUpkeep: 5,
      },
      ram: {
        name: "Battering Ram",
        stats: { attack: 60, defenseInfantry: 35, defenseCavalry: 75, speed: 4, carry: 0 },
        cost: { wood: 920, clay: 370, iron: 510, crop: 75 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Petrobolos",
        stats: { attack: 80, defenseInfantry: 65, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 980, clay: 1400, iron: 620, crop: 95 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Strategos",
        stats: { attack: 50, defenseInfantry: 45, defenseCavalry: 35, speed: 4, carry: 0 },
        cost: { wood: 32000, clay: 28000, iron: 46000, crop: 38000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5900, clay: 5400, iron: 7300, crop: 5600 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Byzantine Hero",
      description: "Theme commander schooled in combined arms and siege.",
      stats: { attack: 110, defenseInfantry: 125, defenseCavalry: 115, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "mongol",
    name: "Mongols",
    era: "Mongol Empire (13th c. CE)",
    region: "Eurasian steppe",
    theme: "Horse-archer dominance, extreme mobility, weak static defense",
    historicalContext:
      "Mongol tumens mastered mounted archery, feigned retreats, and operational mobility across the steppe.",
    keywords: ["mongol", "mongolia", "genghis", "chinggis", "steppe", "horde", "tatar", "yuan"],
    palette: { primary: "#3E2723", secondary: "#C62828", notes: "Steppe leather + blood red" },
    archetype: "cavalry",
    fightingStrengthPerPoint: 80,
    logos: {
      inf_t1: "infantry/arrowhead.svg",
      inf_t2: "infantry/double-shot.svg",
      inf_t3: "infantry/tomahawk.svg",
      scout: "infantry/flying-shuriken.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "animals/pegasus.svg",
      ram: "infantry/war-pick.svg",
      catapult: "powder.svg",
      chief: "infantry/baton.svg",
      settler: "resources/rolled-paper.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 800 },
      inf_t2: { building: "barracks", timeSeconds: 1100 },
      inf_t3: { building: "barracks", timeSeconds: 1200 },
      scout: { building: "barracks", timeSeconds: 1000 },
      cav_t1: { building: "stable", timeSeconds: 1300 },
      cav_t2: { building: "stable", timeSeconds: 1600 },
      cav_t3: { building: "stable", timeSeconds: 1800 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Dismounted Archer",
        description: "Steppe warriors fighting on foot when needed.",
        stats: { attack: 35, defenseInfantry: 25, defenseCavalry: 20, speed: 8, carry: 40 },
        cost: { wood: 90, clay: 70, iron: 50, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Kheshig Guard",
        description: "Household infantry escort — tougher than levy foot.",
        stats: { attack: 50, defenseInfantry: 40, defenseCavalry: 30, speed: 7, carry: 35 },
        cost: { wood: 120, clay: 100, iron: 130, crop: 55 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Siege Levy",
        description: "Conscript engineers and auxiliaries for assaults.",
        stats: { attack: 55, defenseInfantry: 35, defenseCavalry: 25, speed: 6, carry: 45 },
        cost: { wood: 140, clay: 130, iron: 150, crop: 60 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Mangudai Scout",
        stats: { attack: 0, defenseInfantry: 15, defenseCavalry: 15, speed: 18, carry: 0 },
        cost: { wood: 125, clay: 135, iron: 20, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Light Horse Archer",
        description: "Core Mongol arm — speed and harassment.",
        stats: { attack: 130, defenseInfantry: 40, defenseCavalry: 45, speed: 17, carry: 100 },
        cost: { wood: 450, clay: 360, iron: 250, crop: 90 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Heavy Lancers",
        description: "Armored cavalry for the final shock.",
        stats: { attack: 175, defenseInfantry: 70, defenseCavalry: 90, speed: 13, carry: 80 },
        cost: { wood: 520, clay: 560, iron: 700, crop: 160 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Mangudai Elite",
        description: "Veteran tumen horse archers.",
        stats: { attack: 160, defenseInfantry: 55, defenseCavalry: 65, speed: 16, carry: 90 },
        cost: { wood: 500, clay: 480, iron: 520, crop: 150 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Captured Ram",
        stats: { attack: 55, defenseInfantry: 25, defenseCavalry: 65, speed: 4, carry: 0 },
        cost: { wood: 860, clay: 340, iron: 470, crop: 65 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Traction Trebuchet",
        stats: { attack: 75, defenseInfantry: 50, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 930, clay: 1280, iron: 580, crop: 85 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Noyan",
        stats: { attack: 50, defenseInfantry: 35, defenseCavalry: 30, speed: 5, carry: 0 },
        cost: { wood: 29000, clay: 26000, iron: 42000, crop: 35000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5600, clay: 5100, iron: 7000, crop: 5300 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Mongol Hero",
      description: "Ordu commander — operational mobility and horse-archer doctrine.",
      stats: { attack: 115, defenseInfantry: 90, defenseCavalry: 95, speed: 12, carry: 110 },
      cropUpkeep: 6,
    },
  },
  {
    id: "japanese",
    name: "Japanese",
    era: "Sengoku / late medieval Japan (15th–16th c. CE)",
    region: "Japanese archipelago",
    theme: "Ashigaru masses, samurai quality, weak native cavalry tradition",
    historicalContext:
      "Sengoku armies mixed ashigaru pike and arquebus lines with samurai retainers; cavalry existed but infantry decided most battles.",
    keywords: ["japanese", "japan", "samurai", "ashigaru", "sengoku", "shogun", "bushido", "naginata"],
    palette: { primary: "#8B1A1A", secondary: "#F5F0E6", notes: "Lacquer red + rice-paper cream" },
    archetype: "infantry",
    fightingStrengthPerPoint: 90,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/kusarigama.svg",
      inf_t3: "infantry/machete.svg",
      scout: "infantry/shuriken.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "cavalry/donkey.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/baton.svg",
      settler: "resources/wheat-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 960 },
      inf_t2: { building: "barracks", timeSeconds: 1200 },
      inf_t3: { building: "barracks", timeSeconds: 1500 },
      scout: { building: "barracks", timeSeconds: 1100 },
      cav_t1: { building: "stable", timeSeconds: 2000 },
      cav_t2: { building: "stable", timeSeconds: 2400 },
      cav_t3: { building: "stable", timeSeconds: 2500 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Ashigaru Yari",
        description: "Pike ashigaru — backbone of Sengoku armies.",
        stats: { attack: 35, defenseInfantry: 45, defenseCavalry: 55, speed: 6, carry: 40 },
        cost: { wood: 100, clay: 85, iron: 100, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Ashigaru Yumi",
        description: "Bow ashigaru supporting the spear line.",
        stats: { attack: 50, defenseInfantry: 30, defenseCavalry: 25, speed: 7, carry: 30 },
        cost: { wood: 130, clay: 90, iron: 70, crop: 45 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Samurai",
        description: "Elite retainers — costly, versatile melee.",
        stats: { attack: 80, defenseInfantry: 55, defenseCavalry: 40, speed: 7, carry: 45 },
        cost: { wood: 170, clay: 160, iron: 230, crop: 100 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Shinobi Scout",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 10, speed: 16, carry: 0 },
        cost: { wood: 130, clay: 145, iron: 30, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Ki Cavalry",
        stats: { attack: 110, defenseInfantry: 55, defenseCavalry: 50, speed: 14, carry: 90 },
        cost: { wood: 520, clay: 420, iron: 340, crop: 100 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Samurai Cavalry",
        stats: { attack: 160, defenseInfantry: 75, defenseCavalry: 95, speed: 11, carry: 70 },
        cost: { wood: 560, clay: 620, iron: 760, crop: 175 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Hatamoto Horse",
        stats: { attack: 150, defenseInfantry: 70, defenseCavalry: 85, speed: 12, carry: 75 },
        cost: { wood: 540, clay: 580, iron: 700, crop: 160 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Ram",
        stats: { attack: 60, defenseInfantry: 30, defenseCavalry: 75, speed: 4, carry: 0 },
        cost: { wood: 900, clay: 360, iron: 500, crop: 70 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Hōsha",
        stats: { attack: 75, defenseInfantry: 60, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 950, clay: 1350, iron: 600, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Daimyō",
        stats: { attack: 50, defenseInfantry: 40, defenseCavalry: 30, speed: 4, carry: 0 },
        cost: { wood: 30500, clay: 27000, iron: 44500, crop: 37000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5800, clay: 5300, iron: 7200, crop: 5500 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Japanese Hero",
      description: "Sengoku warlord — infantry discipline and retainer quality.",
      stats: { attack: 110, defenseInfantry: 120, defenseCavalry: 95, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "israelite",
    name: "Israelites",
    era: "Iron Age Israel & Judah (c. 1000–586 BCE)",
    region: "Levant / Canaan",
    theme: "Hill-country infantry, slingers, and chariot elites of the kingdoms of Israel and Judah",
    historicalContext:
      "Israelite and Judahite armies mixed tribal levies with royal guards: spearmen and slingers in the highlands, chariots on suitable ground, and fortified-city defense traditions reflected in Judges–Kings narratives and archaeology.",
    keywords: [
      "israelite",
      "israel",
      "judah",
      "hebrew",
      "jewish",
      "judean",
      "david",
      "solomon",
      "canaan",
      "levite",
      "biblical",
    ],
    palette: { primary: "#1A3C6E", secondary: "#C9A227", notes: "Deep indigo + temple gold" },
    archetype: "infantry",
    fightingStrengthPerPoint: 90,
    resourceProductionBonusPercent: 5,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/boomerang.svg",
      inf_t3: "infantry/gladius.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "cavalry/donkey.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/crescent-staff.svg",
      settler: "resources/wheat-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1000 },
      inf_t2: { building: "barracks", timeSeconds: 1200 },
      inf_t3: { building: "barracks", timeSeconds: 1520 },
      scout: { building: "barracks", timeSeconds: 1180 },
      cav_t1: { building: "stable", timeSeconds: 1800 },
      cav_t2: { building: "stable", timeSeconds: 2300 },
      cav_t3: { building: "stable", timeSeconds: 2500 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Levy Spearman",
        description: "Tribal muster with spear and shield — backbone of highland defense.",
        stats: { attack: 35, defenseInfantry: 42, defenseCavalry: 48, speed: 6, carry: 40 },
        cost: { wood: 105, clay: 90, iron: 110, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Slinger",
        description: "Judean and Benjaminite slingers — famous skirmish arm.",
        stats: { attack: 48, defenseInfantry: 28, defenseCavalry: 22, speed: 8, carry: 30 },
        cost: { wood: 125, clay: 85, iron: 55, crop: 40 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Gibbor",
        description: "Royal ‘mighty men’ — elite infantry of the king’s household.",
        stats: { attack: 72, defenseInfantry: 55, defenseCavalry: 40, speed: 7, carry: 45 },
        cost: { wood: 165, clay: 155, iron: 215, crop: 90 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Watchman",
        description: "Hill-country scouts and city lookouts.",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 12, speed: 15, carry: 0 },
        cost: { wood: 130, clay: 145, iron: 25, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Chariot Runner",
        description: "Light escort attached to chariot teams.",
        stats: { attack: 105, defenseInfantry: 50, defenseCavalry: 45, speed: 14, carry: 85 },
        cost: { wood: 490, clay: 400, iron: 300, crop: 95 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Royal Chariot",
        description: "Heavy chariots of the royal stables — strike arm on open ground.",
        stats: { attack: 165, defenseInfantry: 70, defenseCavalry: 90, speed: 11, carry: 65 },
        cost: { wood: 550, clay: 600, iron: 740, crop: 170 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Horse Guard",
        description: "Mounted retainers expanding the older chariot tradition.",
        stats: { attack: 145, defenseInfantry: 65, defenseCavalry: 80, speed: 13, carry: 80 },
        cost: { wood: 520, clay: 540, iron: 620, crop: 150 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Siege Ram",
        stats: { attack: 58, defenseInfantry: 30, defenseCavalry: 72, speed: 4, carry: 0 },
        cost: { wood: 890, clay: 355, iron: 490, crop: 70 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Stone Engine",
        stats: { attack: 72, defenseInfantry: 58, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 940, clay: 1320, iron: 590, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Nasi",
        description: "Prince or appointed governor empowered to receive cities.",
        stats: { attack: 48, defenseInfantry: 42, defenseCavalry: 30, speed: 4, carry: 0 },
        cost: { wood: 30000, clay: 26800, iron: 44000, crop: 36500 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5750, clay: 5250, iron: 7100, crop: 5450 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Israelite Hero",
      description: "Royal captain in the tradition of David’s gibborim — infantry grit and chariot coordination.",
      stats: { attack: 108, defenseInfantry: 118, defenseCavalry: 100, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "axum",
    name: "Axum",
    era: "Kingdom of Aksum (1st–7th c. CE)",
    region: "Ethiopian highlands / Red Sea",
    theme: "Highland spearmen, ivory-trade wealth, and Red Sea projection",
    historicalContext:
      "Aksum controlled highland agriculture and Red Sea trade (ivory, gold, incense), fielding spear infantry and limited cavalry while projecting power into South Arabia and the Nile corridor.",
    keywords: [
      "axum",
      "aksum",
      "aksumite",
      "axumite",
      "ethiopian",
      "ethiopia",
      "eritrea",
      "red sea",
      "nubian",
    ],
    palette: { primary: "#6B2D1A", secondary: "#E8B84A", notes: "Laterite earth + trade gold" },
    archetype: "balanced",
    fightingStrengthPerPoint: 88,
    resourceProductionBonusPercent: 12,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/barbed-spear.svg",
      inf_t3: "infantry/battle-axe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/donkey.svg",
      cav_t2: "cavalry/horse-head.svg",
      cav_t3: "cavalry/camel-head.svg",
      ram: "infantry/war-pick.svg",
      catapult: "powder.svg",
      chief: "infantry/orb-wand.svg",
      settler: "resources/grain.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1100 },
      inf_t2: { building: "barracks", timeSeconds: 1300 },
      inf_t3: { building: "barracks", timeSeconds: 1550 },
      scout: { building: "barracks", timeSeconds: 1200 },
      cav_t1: { building: "stable", timeSeconds: 1700 },
      cav_t2: { building: "stable", timeSeconds: 2100 },
      cav_t3: { building: "stable", timeSeconds: 2400 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Highland Spearman",
        description: "Aksumite levy from the Ethiopian plateau.",
        stats: { attack: 36, defenseInfantry: 40, defenseCavalry: 45, speed: 6, carry: 42 },
        cost: { wood: 108, clay: 92, iron: 115, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Javelin Skirmisher",
        description: "Light troops screening columns on highland roads.",
        stats: { attack: 46, defenseInfantry: 30, defenseCavalry: 28, speed: 8, carry: 35 },
        cost: { wood: 120, clay: 88, iron: 75, crop: 42 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Royal Guard",
        description: "Household infantry of the negus — costly elite foot.",
        stats: { attack: 70, defenseInfantry: 52, defenseCavalry: 38, speed: 6, carry: 48 },
        cost: { wood: 168, clay: 158, iron: 210, crop: 92 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Border Scout",
        stats: { attack: 0, defenseInfantry: 18, defenseCavalry: 12, speed: 16, carry: 0 },
        cost: { wood: 128, clay: 140, iron: 22, crop: 38 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Highland Horse",
        description: "Light cavalry adapted to plateau warfare.",
        stats: { attack: 112, defenseInfantry: 52, defenseCavalry: 48, speed: 15, carry: 92 },
        cost: { wood: 470, clay: 390, iron: 290, crop: 95 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Noble Cavalry",
        stats: { attack: 160, defenseInfantry: 72, defenseCavalry: 92, speed: 11, carry: 70 },
        cost: { wood: 545, clay: 610, iron: 730, crop: 170 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Camel Corps",
        description: "Desert and coastal camelry for Red Sea approaches.",
        stats: { attack: 138, defenseInfantry: 58, defenseCavalry: 68, speed: 12, carry: 115 },
        cost: { wood: 490, clay: 460, iron: 430, crop: 155 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Siege Ram",
        stats: { attack: 58, defenseInfantry: 28, defenseCavalry: 70, speed: 4, carry: 0 },
        cost: { wood: 885, clay: 350, iron: 485, crop: 68 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Stone Thrower",
        stats: { attack: 74, defenseInfantry: 58, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 945, clay: 1330, iron: 595, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Negus",
        description: "Aksumite king or appointed viceroy.",
        stats: { attack: 48, defenseInfantry: 40, defenseCavalry: 32, speed: 4, carry: 0 },
        cost: { wood: 30200, clay: 27200, iron: 44800, crop: 36800 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Colonist",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5700, clay: 5200, iron: 7050, crop: 5400 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Axumite Hero",
      description: "Aksumite war-leader — highland infantry and Red Sea logistics.",
      stats: { attack: 102, defenseInfantry: 112, defenseCavalry: 100, speed: 8, carry: 105 },
      cropUpkeep: 6,
    },
  },
  {
    id: "greek",
    name: "Greeks",
    era: "Classical Greece (5th–4th c. BCE)",
    region: "Aegean / Hellenic city-states",
    theme: "Hoplite phalanx, peltasts, and citizen cavalry — broader Hellas beyond Sparta alone",
    historicalContext:
      "Classical Greek warfare centered on the hoplite phalanx, supported by peltast skirmishers and limited citizen cavalry; city-state rivalry (Athens, Thebes, Corinth, and others) produced varied combined-arms practice distinct from the Spartan mono-focus already in Tevel.",
    keywords: [
      "greek",
      "greece",
      "hellenic",
      "hellas",
      "hoplite",
      "athenian",
      "theban",
      "corinthian",
      "peltast",
      "phalanx",
      "classical",
    ],
    palette: { primary: "#1F4E79", secondary: "#F2F0E6", notes: "Aegean blue + marble white" },
    archetype: "infantry",
    fightingStrengthPerPoint: 92,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/boomerang.svg",
      inf_t3: "infantry/trident.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "animals/ram.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/baton.svg",
      settler: "resources/wheat-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1280 },
      inf_t2: { building: "barracks", timeSeconds: 1400 },
      inf_t3: { building: "barracks", timeSeconds: 1680 },
      scout: { building: "barracks", timeSeconds: 1300 },
      cav_t1: { building: "stable", timeSeconds: 2000 },
      cav_t2: { building: "stable", timeSeconds: 2500 },
      cav_t3: { building: "stable", timeSeconds: 2600 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Hoplite",
        description: "Citizen heavy infantry with aspis and dory — core of the phalanx.",
        stats: { attack: 40, defenseInfantry: 55, defenseCavalry: 60, speed: 5, carry: 40 },
        cost: { wood: 130, clay: 115, iron: 160, crop: 40 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Peltast",
        description: "Javelin light infantry — flexible screen and pursuit.",
        stats: { attack: 45, defenseInfantry: 32, defenseCavalry: 30, speed: 9, carry: 35 },
        cost: { wood: 115, clay: 95, iron: 85, crop: 45 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Ekdromos",
        description: "Mobile hoplites trained to break formation and chase light troops.",
        stats: { attack: 68, defenseInfantry: 48, defenseCavalry: 42, speed: 7, carry: 45 },
        cost: { wood: 160, clay: 150, iron: 200, crop: 85 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Prodromos Scout",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 12, speed: 16, carry: 0 },
        cost: { wood: 140, clay: 155, iron: 25, crop: 42 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Hippeis",
        description: "Citizen cavalry of the wealthier classes.",
        stats: { attack: 118, defenseInfantry: 58, defenseCavalry: 52, speed: 14, carry: 90 },
        cost: { wood: 530, clay: 430, iron: 330, crop: 105 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Companion Horse",
        description: "Heavy strike cavalry in the later classical / Macedonian-influenced mold.",
        stats: { attack: 175, defenseInfantry: 78, defenseCavalry: 100, speed: 11, carry: 70 },
        cost: { wood: 570, clay: 640, iron: 790, crop: 180 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Thessalian Cavalry",
        description: "Finest Greek horsemen — scouting and shock on open ground.",
        stats: { attack: 155, defenseInfantry: 70, defenseCavalry: 88, speed: 13, carry: 85 },
        cost: { wood: 545, clay: 560, iron: 680, crop: 160 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Battering Ram",
        stats: { attack: 60, defenseInfantry: 32, defenseCavalry: 75, speed: 4, carry: 0 },
        cost: { wood: 910, clay: 365, iron: 505, crop: 72 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Lithobolos",
        stats: { attack: 78, defenseInfantry: 62, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 970, clay: 1380, iron: 610, crop: 95 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Strategos",
        description: "Elected or appointed general of the polis.",
        stats: { attack: 50, defenseInfantry: 45, defenseCavalry: 32, speed: 4, carry: 0 },
        cost: { wood: 31500, clay: 27800, iron: 45500, crop: 37500 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5850, clay: 5350, iron: 7250, crop: 5550 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Greek Hero",
      description: "Classical strategos — phalanx discipline and combined-arms flexibility.",
      stats: { attack: 105, defenseInfantry: 125, defenseCavalry: 105, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "slav",
    name: "Slavs",
    era: "Early medieval Slavs (6th–10th c. CE)",
    region: "Eastern Europe / forest-steppe",
    theme: "Forest infantry, shield-wall levies, and light horse on the open fringe",
    historicalContext:
      "Early Slavic warbands fought mainly on foot with spears, axes, and bows from forest settlements, using ambush and raid tactics; cavalry grew as contact with steppe and Byzantine neighbors increased.",
    keywords: [
      "slav",
      "slavic",
      "slavs",
      "sclavene",
      "ante",
      "polish",
      "czech",
      "serbian",
      "russian",
      "kievan",
      "wend",
    ],
    palette: { primary: "#2E5A3C", secondary: "#C4A35A", notes: "Forest green + amber" },
    archetype: "infantry",
    fightingStrengthPerPoint: 85,
    resourceProductionBonusPercent: 8,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/wood-club.svg",
      inf_t3: "infantry/war-axe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/donkey.svg",
      cav_t3: "cavalry/chess-knight.svg",
      ram: "infantry/battered-axe.svg",
      catapult: "powder.svg",
      chief: "infantry/baton.svg",
      settler: "resources/wood-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 880 },
      inf_t2: { building: "barracks", timeSeconds: 1100 },
      inf_t3: { building: "barracks", timeSeconds: 1320 },
      scout: { building: "barracks", timeSeconds: 1120 },
      cav_t1: { building: "stable", timeSeconds: 1600 },
      cav_t2: { building: "stable", timeSeconds: 2000 },
      cav_t3: { building: "stable", timeSeconds: 2200 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 28000 },
    },
    troops: {
      inf_t1: {
        name: "Spear Levy",
        description: "Village muster with spear and round shield.",
        stats: { attack: 35, defenseInfantry: 40, defenseCavalry: 35, speed: 7, carry: 45 },
        cost: { wood: 95, clay: 80, iron: 70, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Axeman",
        description: "Forest fighters with axe and light armor.",
        stats: { attack: 55, defenseInfantry: 35, defenseCavalry: 25, speed: 7, carry: 40 },
        cost: { wood: 115, clay: 95, iron: 130, crop: 50 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Druzhina Foot",
        description: "Princely retinue infantry — better armed household troops.",
        stats: { attack: 70, defenseInfantry: 50, defenseCavalry: 35, speed: 6, carry: 45 },
        cost: { wood: 150, clay: 140, iron: 195, crop: 80 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Forest Scout",
        stats: { attack: 0, defenseInfantry: 18, defenseCavalry: 10, speed: 15, carry: 0 },
        cost: { wood: 120, clay: 130, iron: 20, crop: 35 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Light Horse",
        description: "Raiding cavalry on the forest-steppe fringe.",
        stats: { attack: 105, defenseInfantry: 45, defenseCavalry: 40, speed: 15, carry: 100 },
        cost: { wood: 440, clay: 360, iron: 270, crop: 90 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Druzhina Horse",
        description: "Mounted retainers of the knyaz.",
        stats: { attack: 150, defenseInfantry: 65, defenseCavalry: 80, speed: 12, carry: 75 },
        cost: { wood: 510, clay: 530, iron: 660, crop: 155 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Boyar Cavalry",
        description: "Noble heavy horse — costly shock arm.",
        stats: { attack: 160, defenseInfantry: 72, defenseCavalry: 90, speed: 11, carry: 70 },
        cost: { wood: 530, clay: 560, iron: 700, crop: 165 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Ram",
        stats: { attack: 58, defenseInfantry: 28, defenseCavalry: 70, speed: 4, carry: 0 },
        cost: { wood: 860, clay: 340, iron: 475, crop: 65 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Catapult",
        stats: { attack: 70, defenseInfantry: 52, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 910, clay: 1260, iron: 570, crop: 85 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Knyaz",
        description: "Slavic prince empowered to receive settlements.",
        stats: { attack: 52, defenseInfantry: 38, defenseCavalry: 28, speed: 5, carry: 0 },
        cost: { wood: 28500, clay: 25500, iron: 41000, crop: 34500 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5550, clay: 5050, iron: 6900, crop: 5250 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Slavic Hero",
      description: "Early medieval knyaz — forest infantry and retinue cavalry.",
      stats: { attack: 112, defenseInfantry: 105, defenseCavalry: 90, speed: 9, carry: 110 },
      cropUpkeep: 6,
    },
  },
  {
    id: "balt",
    name: "Balts",
    era: "Baltic tribes (early medieval–13th c. CE)",
    region: "Eastern Baltic / amber coast",
    theme: "Dense-forest infantry, ambush warfare, and stubborn defensive levies",
    historicalContext:
      "Baltic peoples (Prussians, Lithuanians, Latgalians, and kin) fought in wooded terrain with spears, axes, and bows; cavalry remained secondary until the rise of Lithuanian horse in the later Middle Ages.",
    keywords: [
      "balt",
      "baltic",
      "balts",
      "lithuanian",
      "latvian",
      "prussian",
      "samogitian",
      "latgalian",
      "amber",
      "yotvingian",
    ],
    palette: { primary: "#1B4332", secondary: "#D4A017", notes: "Pine green + amber gold" },
    archetype: "infantry",
    fightingStrengthPerPoint: 88,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/battle-axe.svg",
      inf_t3: "infantry/sharp-axe.svg",
      scout: "infantry/boomerang.svg",
      cav_t1: "cavalry/donkey.svg",
      cav_t2: "cavalry/horse-head.svg",
      cav_t3: "cavalry/chess-knight.svg",
      ram: "infantry/war-pick.svg",
      catapult: "powder.svg",
      chief: "infantry/thor-hammer.svg",
      settler: "resources/honeycomb.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 960 },
      inf_t2: { building: "barracks", timeSeconds: 1180 },
      inf_t3: { building: "barracks", timeSeconds: 1400 },
      scout: { building: "barracks", timeSeconds: 1100 },
      cav_t1: { building: "stable", timeSeconds: 1700 },
      cav_t2: { building: "stable", timeSeconds: 2100 },
      cav_t3: { building: "stable", timeSeconds: 2300 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 27500 },
    },
    troops: {
      inf_t1: {
        name: "Spearman",
        description: "Tribal levy for forest defense.",
        stats: { attack: 34, defenseInfantry: 45, defenseCavalry: 40, speed: 6, carry: 40 },
        cost: { wood: 100, clay: 85, iron: 75, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Axeman",
        description: "Close-combat infantry favored in wooded fighting.",
        stats: { attack: 58, defenseInfantry: 38, defenseCavalry: 28, speed: 7, carry: 38 },
        cost: { wood: 120, clay: 100, iron: 140, crop: 52 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Chosen Warrior",
        description: "Elite household fighters — high attack in ambush and melee.",
        stats: { attack: 78, defenseInfantry: 48, defenseCavalry: 32, speed: 7, carry: 42 },
        cost: { wood: 155, clay: 145, iron: 205, crop: 85 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Tracker",
        description: "Forest pathfinders and border watchers.",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 10, speed: 15, carry: 0 },
        cost: { wood: 125, clay: 135, iron: 22, crop: 38 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Light Rider",
        stats: { attack: 100, defenseInfantry: 48, defenseCavalry: 42, speed: 14, carry: 95 },
        cost: { wood: 450, clay: 370, iron: 280, crop: 92 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Noble Horse",
        description: "Emerging Baltic cavalry tradition.",
        stats: { attack: 148, defenseInfantry: 68, defenseCavalry: 85, speed: 12, carry: 72 },
        cost: { wood: 515, clay: 540, iron: 670, crop: 158 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Raid Cavalry",
        stats: { attack: 155, defenseInfantry: 62, defenseCavalry: 78, speed: 13, carry: 88 },
        cost: { wood: 525, clay: 520, iron: 640, crop: 150 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Ram",
        stats: { attack: 60, defenseInfantry: 28, defenseCavalry: 72, speed: 4, carry: 0 },
        cost: { wood: 870, clay: 345, iron: 480, crop: 68 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Catapult",
        stats: { attack: 72, defenseInfantry: 55, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 920, clay: 1280, iron: 575, crop: 88 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Kunigas",
        description: "Baltic chieftain or duke.",
        stats: { attack: 50, defenseInfantry: 40, defenseCavalry: 28, speed: 4, carry: 0 },
        cost: { wood: 29000, clay: 26000, iron: 42000, crop: 35000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5600, clay: 5100, iron: 6950, crop: 5300 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Baltic Hero",
      description: "Forest war-leader — ambush infantry and stubborn defense.",
      stats: { attack: 115, defenseInfantry: 110, defenseCavalry: 88, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "dacian",
    name: "Dacians",
    era: "Dacian Kingdom (1st c. BCE–2nd c. CE)",
    region: "Carpathians / lower Danube",
    theme: "Falx infantry, mountain defense, and Sarmatian-allied horse",
    historicalContext:
      "Dacian armies under leaders such as Burebista and Decebalus combined falx-armed infantry and fortress warfare in the Carpathians with allied Sarmatian cavalry, famously resisting Rome in Trajan’s wars.",
    keywords: [
      "dacian",
      "dacia",
      "dacians",
      "decebalus",
      "burebista",
      "falx",
      "carpathian",
      "thracian",
      "getae",
      "sarmatian",
    ],
    palette: { primary: "#5C1A1A", secondary: "#D4AF37", notes: "Carpathian crimson + gold" },
    archetype: "infantry",
    fightingStrengthPerPoint: 90,
    logos: {
      inf_t1: "infantry/stone-spear.svg",
      inf_t2: "infantry/scythe.svg",
      inf_t3: "infantry/battle-axe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "cavalry/chess-knight.svg",
      cav_t3: "animals/ram.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/flanged-mace.svg",
      settler: "resources/stone-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 1040 },
      inf_t2: { building: "barracks", timeSeconds: 1240 },
      inf_t3: { building: "barracks", timeSeconds: 1480 },
      scout: { building: "barracks", timeSeconds: 1200 },
      cav_t1: { building: "stable", timeSeconds: 1750 },
      cav_t2: { building: "stable", timeSeconds: 2200 },
      cav_t3: { building: "stable", timeSeconds: 2400 },
      ram: { building: "workshop", timeSeconds: 4600 },
      catapult: { building: "workshop", timeSeconds: 9000 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Spearman",
        description: "Dacian levy with spear and shield.",
        stats: { attack: 36, defenseInfantry: 42, defenseCavalry: 40, speed: 6, carry: 42 },
        cost: { wood: 105, clay: 90, iron: 100, crop: 35 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Falxman",
        description: "Two-handed falx infantry — feared by Roman legionaries.",
        stats: { attack: 75, defenseInfantry: 30, defenseCavalry: 25, speed: 6, carry: 35 },
        cost: { wood: 130, clay: 110, iron: 170, crop: 60 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Comati Warrior",
        description: "Long-haired free warriors — versatile mountain infantry.",
        stats: { attack: 65, defenseInfantry: 48, defenseCavalry: 38, speed: 7, carry: 45 },
        cost: { wood: 155, clay: 145, iron: 190, crop: 80 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Mountain Scout",
        stats: { attack: 0, defenseInfantry: 20, defenseCavalry: 12, speed: 15, carry: 0 },
        cost: { wood: 130, clay: 145, iron: 25, crop: 40 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Dacian Horse",
        stats: { attack: 110, defenseInfantry: 52, defenseCavalry: 48, speed: 14, carry: 90 },
        cost: { wood: 480, clay: 395, iron: 300, crop: 95 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Sarmatian Ally",
        description: "Allied steppe cavalry — lance and bow.",
        stats: { attack: 170, defenseInfantry: 70, defenseCavalry: 95, speed: 12, carry: 75 },
        cost: { wood: 540, clay: 600, iron: 750, crop: 175 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Noble Cavalry",
        stats: { attack: 150, defenseInfantry: 68, defenseCavalry: 85, speed: 12, carry: 80 },
        cost: { wood: 525, clay: 550, iron: 680, crop: 155 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Siege Ram",
        stats: { attack: 62, defenseInfantry: 30, defenseCavalry: 75, speed: 4, carry: 0 },
        cost: { wood: 900, clay: 360, iron: 500, crop: 70 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Stone Thrower",
        stats: { attack: 75, defenseInfantry: 58, defenseCavalry: 10, speed: 3, carry: 0 },
        cost: { wood: 950, clay: 1340, iron: 600, crop: 90 },
        cropUpkeep: 6,
      },
      chief: {
        name: "King",
        description: "Dacian king or appointed commander (tarabostes nobility).",
        stats: { attack: 55, defenseInfantry: 42, defenseCavalry: 30, speed: 4, carry: 0 },
        cost: { wood: 30000, clay: 27000, iron: 44500, crop: 36500 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Settler",
        stats: { attack: 0, defenseInfantry: 80, defenseCavalry: 80, speed: 5, carry: 3000 },
        cost: { wood: 5750, clay: 5250, iron: 7100, crop: 5450 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Dacian Hero",
      description: "Carpathian war-leader — falx shock and mountain defense.",
      stats: { attack: 118, defenseInfantry: 108, defenseCavalry: 95, speed: 8, carry: 100 },
      cropUpkeep: 6,
    },
  },
  {
    id: "undead",
    name: "Undead",
    era: "Fantasy / necromantic",
    region: "Grave-realms / cursed marches",
    theme:
      "Dread host stronger than Natars and oasis Nature — relentless bone waves, spectral scouts, and catastrophic cavalry",
    historicalContext:
      "A necromantic host of raised dead, wights, and cursed riders. Fantasy faction (not historical): infantry waves and dread cavalry that outmatch Natarian guards and oasis beasts, with siege and lich-lords scaled above Nature titans.",
    keywords: [
      "undead",
      "undead tribe",
      "zombie",
      "skeleton",
      "necromancer",
      "necromantic",
      "wight",
      "lich",
      "ghoul",
      "revenant",
      "death",
      "grave",
    ],
    palette: { primary: "#1A1A2E", secondary: "#6BCB77", notes: "Midnight crypt + corpse-glow green" },
    archetype: "raider",
    fightingStrengthPerPoint: 110,
    logos: {
      inf_t1: "infantry/bone-mace.svg",
      inf_t2: "infantry/sacrificial-dagger.svg",
      inf_t3: "infantry/scythe.svg",
      scout: "infantry/heavy-arrow.svg",
      cav_t1: "cavalry/horse-head.svg",
      cav_t2: "animals/ram.svg",
      cav_t3: "cavalry/donkey.svg",
      ram: "infantry/crowbar.svg",
      catapult: "powder.svg",
      chief: "infantry/orb-wand.svg",
      settler: "resources/stone-pile.svg",
    },
    training: {
      inf_t1: { building: "barracks", timeSeconds: 900 },
      inf_t2: { building: "barracks", timeSeconds: 1100 },
      inf_t3: { building: "barracks", timeSeconds: 1500 },
      scout: { building: "barracks", timeSeconds: 1150 },
      cav_t1: { building: "stable", timeSeconds: 1700 },
      cav_t2: { building: "stable", timeSeconds: 2300 },
      cav_t3: { building: "stable", timeSeconds: 2550 },
      ram: { building: "workshop", timeSeconds: 4400 },
      catapult: { building: "workshop", timeSeconds: 8800 },
      chief: { building: "residence", timeSeconds: 90720 },
      settler: { building: "residence", timeSeconds: 26920 },
    },
    troops: {
      inf_t1: {
        name: "Skeleton Levy",
        description: "Rattling bone levy — cheap pressure that still hits harder than oasis vermin.",
        stats: { attack: 45, defenseInfantry: 42, defenseCavalry: 38, speed: 6, carry: 40 },
        cost: { wood: 85, clay: 70, iron: 95, crop: 25 },
        cropUpkeep: 1,
      },
      inf_t2: {
        name: "Ghoul",
        description: "Flesh-hungry raiders — outpace Natarian thorns and tear lines open.",
        stats: { attack: 80, defenseInfantry: 42, defenseCavalry: 35, speed: 8, carry: 35 },
        cost: { wood: 115, clay: 95, iron: 130, crop: 45 },
        cropUpkeep: 1,
      },
      inf_t3: {
        name: "Wight",
        description: "Grave-bound elites — chill blades that outmatch Natarian guardsmen.",
        stats: { attack: 120, defenseInfantry: 100, defenseCavalry: 85, speed: 7, carry: 45 },
        cost: { wood: 150, clay: 135, iron: 200, crop: 75 },
        cropUpkeep: 1,
      },
      scout: {
        name: "Shade",
        description: "Spectral scout — faster and harder to pin than living eyes.",
        stats: { attack: 0, defenseInfantry: 28, defenseCavalry: 22, speed: 19, carry: 0 },
        cost: { wood: 120, clay: 140, iron: 20, crop: 35 },
        cropUpkeep: 2,
      },
      cav_t1: {
        name: "Bone Rider",
        description: "Skeletal light horse — mounted pressure above Natarian axeriders.",
        stats: { attack: 175, defenseInfantry: 95, defenseCavalry: 65, speed: 15, carry: 95 },
        cost: { wood: 430, clay: 360, iron: 280, crop: 85 },
        cropUpkeep: 3,
      },
      cav_t2: {
        name: "Death Knight",
        description: "Cursed heavy cavalry — dread charge that breaks Natarian knights.",
        stats: { attack: 200, defenseInfantry: 155, defenseCavalry: 110, speed: 12, carry: 70 },
        cost: { wood: 520, clay: 590, iron: 740, crop: 170 },
        cropUpkeep: 4,
      },
      cav_t3: {
        name: "Black Steed",
        description: "Night-mares of the necropolis — stronger than Natarian lancers.",
        stats: { attack: 185, defenseInfantry: 125, defenseCavalry: 90, speed: 13, carry: 80 },
        cost: { wood: 500, clay: 520, iron: 640, crop: 145 },
        cropUpkeep: 4,
      },
      ram: {
        name: "Bone Ram",
        description: "Ossuary colossus — bone siege that crushes walls harder than oasis crocodiles.",
        stats: { attack: 480, defenseInfantry: 400, defenseCavalry: 270, speed: 4, carry: 0 },
        cost: { wood: 850, clay: 340, iron: 480, crop: 65 },
        cropUpkeep: 3,
      },
      catapult: {
        name: "Tomb Catapult",
        description: "Hurls crypt-stone with force beyond oasis tigers.",
        stats: { attack: 230, defenseInfantry: 185, defenseCavalry: 270, speed: 3, carry: 0 },
        cost: { wood: 920, clay: 1300, iron: 580, crop: 85 },
        cropUpkeep: 6,
      },
      chief: {
        name: "Lich",
        description: "Arch-lich emperor — outpowers Nature elephants and binds villages to the grave.",
        stats: { attack: 650, defenseInfantry: 470, defenseCavalry: 550, speed: 4, carry: 0 },
        cost: { wood: 29500, clay: 26500, iron: 43000, crop: 35000 },
        cropUpkeep: 5,
      },
      settler: {
        name: "Necropolis Settler",
        description: "Raise a new crypt-colony from barren ground — fortified undead settlers.",
        stats: { attack: 0, defenseInfantry: 95, defenseCavalry: 95, speed: 5, carry: 3000 },
        cost: { wood: 5600, clay: 5100, iron: 7000, crop: 5300 },
        cropUpkeep: 1,
      },
    },
    hero: {
      name: "Death Knight Hero",
      description: "Deathlord of the grave — stronger than Natarian warlords and primal oasis spirits.",
      stats: { attack: 320, defenseInfantry: 270, defenseCavalry: 300, speed: 10, carry: 120 },
      cropUpkeep: 6,
    },
  },
];

const REFS = [
  "inf_t1",
  "inf_t2",
  "inf_t3",
  "scout",
  "cav_t1",
  "cav_t2",
  "cav_t3",
  "ram",
  "catapult",
  "chief",
  "settler",
];

/**
 * @param {string} query
 * @returns {CultureProfile | null}
 */
export function matchProfile(query) {
  const q = String(query || "")
    .trim()
    .toLowerCase();
  if (!q) return null;
  for (const p of CULTURE_PROFILES) {
    if (p.id === q || p.name.toLowerCase() === q) return p;
  }
  let best = null;
  let bestScore = 0;
  for (const p of CULTURE_PROFILES) {
    let score = 0;
    for (const kw of p.keywords) {
      if (q.includes(kw) || kw.includes(q)) score += kw.length;
    }
    if (q.includes(p.name.toLowerCase())) score += 20;
    if (score > bestScore) {
      bestScore = score;
      best = p;
    }
  }
  return bestScore > 0 ? best : null;
}

/** @returns {{ id: string, name: string, era: string, region: string, theme: string, historicalContext: string, archetype: string, palette: object }[]} */
export function listProfileSummaries() {
  return CULTURE_PROFILES.map((p) => ({
    id: p.id,
    name: p.name,
    era: p.era,
    region: p.region,
    theme: p.theme,
    historicalContext: p.historicalContext,
    archetype: p.archetype,
    palette: p.palette,
  }));
}

export function getProfile(id) {
  return CULTURE_PROFILES.find((p) => p.id === id) || null;
}

export { REFS };
